### PR TITLE
test: support packet cache checks in WordPress

### LINKED ISSUE #3211: Fix packet cache smoke test under real WordPress
## Problem

The packet lifecycle cache smoke test introduced with #3208 passes standalone but fatals in Homeboy's real-WordPress Codebox runner because it unconditionally redeclares WordPress functions such as `wp_json_encode()`. The failed test phase then continues through the full smoke inventory and exhausts the 1500-second CI budget.

## Expected

- Smoke helpers are defined only when WordPress has not already loaded them.
- In a real WordPress runtime, the test verifies pre-commit cache stability and post-commit invalidation through the actual object-cache API.
- The packet lifecycle audit introduces no new duplication, constant-bypass, or file-size findings.

## Evidence

Homeboy run `31912008782`, job `95078650338`:

```text
Fatal error: Cannot redeclare wp_json_encode() ... tests/engine-transaction-cache-smoke.php on line 27
HOST_SMOKE_FAIL:tests/engine-transaction-cache-smoke.php:exit=1
```

Related: #3206, #3208

### PR DESCRIPTION
**Pull request by chubes4**
## Summary
- make the packet cache smoke test safe when WordPress has already loaded global helpers
- verify pre-commit cache stability and post-commit invalidation through the real object-cache API in WordPress runtimes
- remove the audit findings introduced by #3208 without changing packet disposition behavior

## Verification
- Homeboy lint: zero findings
- Homeboy audit: zero introduced findings
- packet cache, 52 -> 27 -> 25 routing, and reconciliation smoke contracts pass locally
- `git diff --check` passes

Fixes #3211
Related: #3206, #3208

AI assistance: Used to diagnose failed Homeboy evidence, adapt the smoke test for standalone and real-WordPress execution, and verify the audit/lint gates.

### CODE REVIEW

**Comment by chubes4** [comment]
CI test-shard failure is external to this PR. All four shards execute zero tests and fail in ~1.2s with the identical Homeboy bootstrap error:

```text
Error: Cannot find module '../../../agent-runtimes/wp-codebox/lib/wp-codebox-runtime-selection.js'
Require stack:
- /home/runner/.config/homeboy/extensions/wordpress/scripts/test/wp-codebox-phpunit-adapter.mjs
```

Tracked upstream as Extra-Chill/homeboy#12585. Candidate lint and refactor passed; focused standalone and WordPress-loaded cache smoke verification passed locally. Awaiting the independent candidate audit result before merge.
